version: "3.9"

services:
  api:
    env_file:
      - .env
    build: ./api
    container_name: "api"
    ports:
      - 3000:3000
    environment:
      POSTGRES_DATABASE: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_HOST: "db"
    volumes:
      - ./api/src:/usr/app/src:cached
  
  db:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DATABASE: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./_volumes:/var/lib/postgresql/data